'use client'

import { useState, useRef } from 'react'

export interface BrandingConfig {
  logoUrl: string | null
  companyName: string
  subtitle: string
  primaryColor: string
  secondaryColor: string
  reportFooter: string
}

const DEFAULTS: BrandingConfig = {
  logoUrl: null,
  companyName: 'r-Potential',
  subtitle: 'Powered by FuzeBox AI',
  primaryColor: '#D4AF37',
  secondaryColor: '#0A1628',
  reportFooter: 'Generated by VIPPlay Agent Telemetry',
}

interface BrandingFormProps {
  config: BrandingConfig
  onChange: (config: BrandingConfig) => void
  onApply: () => void
  onReset: () => void
}

export function BrandingForm({ config, onChange, onApply, onReset }: BrandingFormProps) {
  const fileRef = useRef<HTMLInputElement>(null)

  const update = (key: keyof BrandingConfig, value: string) => {
    onChange({ ...config, [key]: value })
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const url = URL.createObjectURL(file)
    onChange({ ...config, logoUrl: url })
  }

  const inputClass =
    'w-full px-3 py-2 rounded-lg border text-sm focus:outline-none focus:ring-2 focus:ring-[#D4AF37]'

  return (
    <div className="card flex flex-col gap-5">
      <h2
        className="text-xs font-semibold uppercase"
        style={{ color: '#64748B', letterSpacing: '0.08em' }}
      >
        Configuration
      </h2>

      {/* Logo upload */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Logo
        </label>
        <div className="flex items-center gap-3">
          <div
            className="w-12 h-12 rounded-lg flex items-center justify-center text-sm font-bold overflow-hidden"
            style={{
              background: config.logoUrl ? 'transparent' : config.primaryColor,
              color: config.secondaryColor,
              border: '1px solid #E2E8F0',
            }}
          >
            {config.logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={config.logoUrl} alt="Logo" className="w-full h-full object-cover" />
            ) : (
              <span style={{ fontSize: 20 }}>&#9670;</span>
            )}
          </div>
          <button
            onClick={() => fileRef.current?.click()}
            className="px-3 py-1.5 rounded-lg border text-xs font-medium cursor-pointer transition-colors"
            style={{ borderColor: '#E2E8F0', color: '#0A1628' }}
          >
            Upload Logo
          </button>
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            onChange={handleFileChange}
            className="hidden"
          />
        </div>
      </div>

      {/* Company name */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Company Name
        </label>
        <input
          type="text"
          value={config.companyName}
          onChange={e => update('companyName', e.target.value)}
          className={inputClass}
          style={{ borderColor: '#E2E8F0' }}
        />
      </div>

      {/* Subtitle */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Subtitle
        </label>
        <input
          type="text"
          value={config.subtitle}
          onChange={e => update('subtitle', e.target.value)}
          className={inputClass}
          style={{ borderColor: '#E2E8F0' }}
        />
      </div>

      {/* Primary color */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Primary Color
        </label>
        <div className="flex items-center gap-3">
          <input
            type="color"
            value={config.primaryColor}
            onChange={e => update('primaryColor', e.target.value)}
            className="w-10 h-10 rounded-lg border cursor-pointer"
            style={{ borderColor: '#E2E8F0' }}
          />
          <input
            type="text"
            value={config.primaryColor}
            onChange={e => update('primaryColor', e.target.value)}
            className={inputClass}
            style={{ borderColor: '#E2E8F0', maxWidth: 140, fontFamily: 'var(--font-mono-jb)' }}
          />
        </div>
      </div>

      {/* Secondary color */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Secondary Color
        </label>
        <div className="flex items-center gap-3">
          <input
            type="color"
            value={config.secondaryColor}
            onChange={e => update('secondaryColor', e.target.value)}
            className="w-10 h-10 rounded-lg border cursor-pointer"
            style={{ borderColor: '#E2E8F0' }}
          />
          <input
            type="text"
            value={config.secondaryColor}
            onChange={e => update('secondaryColor', e.target.value)}
            className={inputClass}
            style={{ borderColor: '#E2E8F0', maxWidth: 140, fontFamily: 'var(--font-mono-jb)' }}
          />
        </div>
      </div>

      {/* Report footer */}
      <div>
        <label className="text-sm font-medium mb-1 block" style={{ color: '#0A1628' }}>
          Report Footer Text
        </label>
        <input
          type="text"
          value={config.reportFooter}
          onChange={e => update('reportFooter', e.target.value)}
          className={inputClass}
          style={{ borderColor: '#E2E8F0' }}
        />
      </div>

      {/* Actions */}
      <div className="flex items-center gap-3 pt-2">
        <button
          onClick={onApply}
          className="px-5 py-2.5 rounded-lg text-sm font-semibold cursor-pointer transition-colors"
          style={{ background: config.primaryColor, color: '#FFFFFF' }}
        >
          Apply Branding
        </button>
        <button
          onClick={onReset}
          className="px-5 py-2.5 rounded-lg border text-sm font-medium cursor-pointer transition-colors"
          style={{ borderColor: '#E2E8F0', color: '#64748B' }}
        >
          Reset to Default
        </button>
      </div>
    </div>
  )
}

export { DEFAULTS as BRANDING_DEFAULTS }
