import type { AEOSSkill, ExecutionPath } from '@/types/aeos'

const ALL_AGENTS: ExecutionPath[] = [
  'anthropic_agent',
  'openai_agent',
  'google_vertex_agent',
  'salesforce_agent',
  'cloudflare_agent',
  'uniphore_agent',
]
const HYBRIDS: ExecutionPath[] = ['hybrid_anthropic_human', 'hybrid_openai_human']

function perf(success: number, cost: number, latency: number) {
  return { success_rate: success, avg_cost_usd: cost, avg_latency_ms: latency }
}

export const SKILLS: AEOSSkill[] = [
  // ── auto_diag (14) ──────────────────────────────────────
  {
    skill_id: 'skill_brake_diag_v3',
    name: 'Brake System Diagnosis',
    family: 'auto_diag',
    description: 'Diagnose brake squeal, vibration, pad wear; recommend replacement plan.',
    allowed_paths: ['human', 'anthropic_agent', 'hybrid_anthropic_human'],
    required_tools: ['service_bulletin_lookup', 'dtc_reader'],
    governance_tags: ['safety_relevant', 'auto_safety', 'strategic_skill'],
    strategic_weight: 0.74,
    drift_risk: 0.18,
    performance: {
      anthropic_agent: perf(0.78, 12.5, 1800),
      hybrid_anthropic_human: perf(0.94, 28.5, 4200),
      human: perf(0.96, 85, 9000),
    },
  },
  {
    skill_id: 'skill_engine_misfire_diag_v2',
    name: 'Engine Misfire Diagnosis',
    family: 'auto_diag',
    description: 'P0300 cluster diagnosis; root-cause across plugs, coils, injectors, vacuum.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human', 'human'],
    required_tools: ['service_bulletin_lookup', 'dtc_reader', 'live_data_capture'],
    governance_tags: ['safety_relevant', 'auto_safety'],
    strategic_weight: 0.62,
    drift_risk: 0.22,
    performance: {
      anthropic_agent: perf(0.82, 14.2, 2100),
      openai_agent: perf(0.80, 13.1, 1900),
      hybrid_anthropic_human: perf(0.92, 31.0, 4500),
      human: perf(0.95, 92, 9500),
    },
  },
  {
    skill_id: 'skill_transmission_shudder_v1',
    name: 'Transmission Shudder Diagnosis',
    family: 'auto_diag',
    description: 'Torque-converter shudder identification at low-speed lockup.',
    allowed_paths: ['anthropic_agent', 'hybrid_anthropic_human', 'human'],
    required_tools: ['service_bulletin_lookup', 'fluid_analyzer'],
    governance_tags: ['safety_relevant', 'auto_safety'],
    strategic_weight: 0.58,
    drift_risk: 0.31,
    performance: {
      anthropic_agent: perf(0.71, 15.0, 2200),
      hybrid_anthropic_human: perf(0.89, 33.5, 4800),
      human: perf(0.93, 105, 10200),
    },
  },
  {
    skill_id: 'skill_adas_calibration_v2',
    name: 'ADAS Calibration Verification',
    family: 'auto_diag',
    description: 'Verify cameras/radars are within calibration after windshield replacement.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['service_bulletin_lookup', 'adas_calibration_tool'],
    governance_tags: ['safety_relevant', 'auto_safety', 'strategic_skill'],
    strategic_weight: 0.71,
    drift_risk: 0.12,
    performance: {
      hybrid_anthropic_human: perf(0.91, 42.0, 5400),
      human: perf(0.97, 145, 12000),
    },
  },
  {
    skill_id: 'skill_battery_health_v1',
    name: 'EV Battery Health Assessment',
    family: 'auto_diag',
    description: 'State-of-health estimate, cell-level imbalance, derate prediction.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'google_vertex_agent', 'hybrid_anthropic_human'],
    required_tools: ['battery_telemetry_api', 'service_bulletin_lookup'],
    governance_tags: ['safety_relevant'],
    strategic_weight: 0.55,
    drift_risk: 0.26,
    performance: {
      anthropic_agent: perf(0.84, 11.5, 1700),
      google_vertex_agent: perf(0.83, 10.8, 1850),
      hybrid_anthropic_human: perf(0.93, 28.0, 4100),
    },
  },
  {
    skill_id: 'skill_hvac_diag_v1',
    name: 'HVAC System Diagnosis',
    family: 'auto_diag',
    description: 'Refrigerant leak, blower, climate-control logic.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human', 'human'],
    required_tools: ['service_bulletin_lookup', 'leak_detector'],
    governance_tags: [],
    strategic_weight: 0.32,
    drift_risk: 0.14,
    performance: {
      anthropic_agent: perf(0.86, 8.5, 1400),
      openai_agent: perf(0.85, 7.9, 1300),
      hybrid_anthropic_human: perf(0.94, 22.0, 3500),
      human: perf(0.96, 75, 8000),
    },
  },
  {
    skill_id: 'skill_suspension_diag_v1',
    name: 'Suspension & Alignment Diagnosis',
    family: 'auto_diag',
    description: 'Strut wear, alignment off-spec, tire-wear pattern analysis.',
    allowed_paths: ['anthropic_agent', 'hybrid_anthropic_human', 'human'],
    required_tools: ['alignment_tool', 'service_bulletin_lookup'],
    governance_tags: ['safety_relevant'],
    strategic_weight: 0.45,
    drift_risk: 0.19,
    performance: {
      anthropic_agent: perf(0.79, 10.2, 1600),
      hybrid_anthropic_human: perf(0.92, 26.5, 3900),
      human: perf(0.95, 88, 9200),
    },
  },
  {
    skill_id: 'skill_electrical_short_v1',
    name: 'Electrical Short Diagnosis',
    family: 'auto_diag',
    description: 'Parasitic draw, harness chafing, ground-fault localization.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['multimeter_api', 'wiring_diagram_lookup'],
    governance_tags: ['safety_relevant'],
    strategic_weight: 0.61,
    drift_risk: 0.34,
    performance: {
      hybrid_anthropic_human: perf(0.87, 38.0, 5100),
      human: perf(0.93, 115, 10800),
    },
  },
  {
    skill_id: 'skill_emissions_diag_v1',
    name: 'Emissions Diagnostic Triage',
    family: 'auto_diag',
    description: 'EVAP, EGR, catalyst-efficiency code triage.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['service_bulletin_lookup', 'dtc_reader'],
    governance_tags: ['regulatory'],
    strategic_weight: 0.41,
    drift_risk: 0.16,
    performance: {
      anthropic_agent: perf(0.83, 9.5, 1500),
      openai_agent: perf(0.82, 9.0, 1450),
      hybrid_anthropic_human: perf(0.93, 24.5, 3700),
    },
  },
  {
    skill_id: 'skill_ev_charging_diag_v1',
    name: 'EV Charging-Path Diagnosis',
    family: 'auto_diag',
    description: 'On-board charger, contactor, inlet thermal events.',
    allowed_paths: ['anthropic_agent', 'google_vertex_agent', 'hybrid_anthropic_human'],
    required_tools: ['battery_telemetry_api', 'thermal_log_reader'],
    governance_tags: ['safety_relevant'],
    strategic_weight: 0.52,
    drift_risk: 0.27,
    performance: {
      anthropic_agent: perf(0.81, 12.0, 1850),
      google_vertex_agent: perf(0.80, 11.2, 1900),
      hybrid_anthropic_human: perf(0.92, 30.0, 4400),
    },
  },
  {
    skill_id: 'skill_steering_diag_v1',
    name: 'Steering & EPS Diagnosis',
    family: 'auto_diag',
    description: 'EPS torque-sensor faults; steering rack play.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['eps_diag_tool', 'service_bulletin_lookup'],
    governance_tags: ['safety_relevant', 'auto_safety'],
    strategic_weight: 0.66,
    drift_risk: 0.21,
    performance: {
      hybrid_anthropic_human: perf(0.90, 36.0, 4900),
      human: perf(0.94, 110, 10300),
    },
  },
  {
    skill_id: 'skill_infotainment_diag_v1',
    name: 'Infotainment Diagnosis',
    family: 'auto_diag',
    description: 'Head-unit, OTA, app-pairing failures.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'cloudflare_agent'],
    required_tools: ['ota_log_reader'],
    governance_tags: ['customer_facing'],
    strategic_weight: 0.28,
    drift_risk: 0.11,
    performance: {
      anthropic_agent: perf(0.88, 6.5, 1100),
      openai_agent: perf(0.87, 6.0, 1050),
      cloudflare_agent: perf(0.84, 4.2, 950),
    },
  },
  {
    skill_id: 'skill_recall_lookup_v1',
    name: 'Recall & TSB Lookup',
    family: 'auto_diag',
    description: 'Cross-reference VIN against open recalls and TSBs.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'cloudflare_agent'],
    required_tools: ['service_bulletin_lookup', 'recall_db'],
    governance_tags: ['regulatory'],
    strategic_weight: 0.36,
    drift_risk: 0.08,
    performance: {
      anthropic_agent: perf(0.94, 5.0, 900),
      openai_agent: perf(0.93, 4.5, 850),
      cloudflare_agent: perf(0.90, 2.8, 750),
    },
  },
  {
    skill_id: 'skill_warranty_eligibility_v1',
    name: 'Warranty Eligibility Determination',
    family: 'auto_diag',
    description: 'Determine warranty/extended-warranty/recall coverage for a repair.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['warranty_db', 'recall_db'],
    governance_tags: ['regulatory', 'customer_facing'],
    strategic_weight: 0.39,
    drift_risk: 0.13,
    performance: {
      anthropic_agent: perf(0.86, 7.5, 1200),
      openai_agent: perf(0.85, 7.0, 1150),
      hybrid_anthropic_human: perf(0.94, 21.0, 3400),
    },
  },

  // ── auto_repair (5) ────────────────────────────────────
  {
    skill_id: 'skill_brake_pad_replace_v1',
    name: 'Brake Pad Replacement Plan',
    family: 'auto_repair',
    description: 'Replacement procedure, torque specs, bedding-in protocol.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['service_bulletin_lookup', 'torque_spec_db'],
    governance_tags: ['safety_relevant', 'auto_safety'],
    strategic_weight: 0.48,
    drift_risk: 0.10,
    performance: {
      hybrid_anthropic_human: perf(0.96, 32.0, 4600),
      human: perf(0.98, 95, 9500),
    },
  },
  {
    skill_id: 'skill_oil_change_v1',
    name: 'Oil Change Service',
    family: 'auto_repair',
    description: 'Standard oil-change procedure with spec lookup.',
    allowed_paths: ['human', 'hybrid_anthropic_human'],
    required_tools: ['oil_spec_db'],
    governance_tags: [],
    strategic_weight: 0.18,
    drift_risk: 0.05,
    performance: {
      hybrid_anthropic_human: perf(0.97, 12.0, 2100),
      human: perf(0.98, 45, 5500),
    },
  },
  {
    skill_id: 'skill_tire_rotation_v1',
    name: 'Tire Rotation & Inspection',
    family: 'auto_repair',
    description: 'Cross-rotation pattern, tread-depth checks.',
    allowed_paths: ['human'],
    required_tools: ['tire_gauge'],
    governance_tags: [],
    strategic_weight: 0.15,
    drift_risk: 0.04,
    performance: { human: perf(0.99, 38, 4500) },
  },
  {
    skill_id: 'skill_alignment_service_v1',
    name: 'Wheel Alignment Service',
    family: 'auto_repair',
    description: 'Camber/caster/toe set to OEM spec.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['alignment_tool', 'oem_spec_db'],
    governance_tags: ['safety_relevant'],
    strategic_weight: 0.41,
    drift_risk: 0.09,
    performance: {
      hybrid_anthropic_human: perf(0.95, 28.0, 4200),
      human: perf(0.97, 95, 9000),
    },
  },
  {
    skill_id: 'skill_battery_replace_v1',
    name: 'Battery Replacement (12V)',
    family: 'auto_repair',
    description: 'Spec-match, registration with BMS.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['battery_registration_tool'],
    governance_tags: [],
    strategic_weight: 0.22,
    drift_risk: 0.07,
    performance: {
      hybrid_anthropic_human: perf(0.96, 14.0, 2400),
      human: perf(0.98, 55, 6200),
    },
  },

  // ── cx_triage (5) ──────────────────────────────────────
  {
    skill_id: 'skill_angry_customer_triage_v2',
    name: 'Angry Customer Triage',
    family: 'cx_triage',
    description: 'De-escalate, classify, route. Empathy + accuracy required.',
    allowed_paths: ['hybrid_openai_human', 'human', 'uniphore_agent', 'openai_agent'],
    required_tools: ['crm_lookup', 'sentiment_analyzer'],
    governance_tags: ['customer_facing', 'gdpr_sensitive'],
    strategic_weight: 0.51,
    drift_risk: 0.24,
    performance: {
      uniphore_agent: perf(0.76, 5.5, 1300),
      openai_agent: perf(0.74, 6.8, 1450),
      hybrid_openai_human: perf(0.92, 25.0, 4000),
      human: perf(0.95, 88, 9500),
    },
  },
  {
    skill_id: 'skill_billing_dispute_v1',
    name: 'Billing Dispute Resolution',
    family: 'cx_triage',
    description: 'Investigate, classify, refund / credit.',
    allowed_paths: ['hybrid_openai_human', 'human'],
    required_tools: ['crm_lookup', 'billing_db'],
    governance_tags: ['customer_facing', 'regulatory'],
    strategic_weight: 0.44,
    drift_risk: 0.17,
    performance: {
      hybrid_openai_human: perf(0.90, 18.0, 3100),
      human: perf(0.94, 78, 8200),
    },
  },
  {
    skill_id: 'skill_appointment_scheduling_v1',
    name: 'Service Appointment Scheduling',
    family: 'cx_triage',
    description: 'Slot match, capacity, customer comms.',
    allowed_paths: ['openai_agent', 'salesforce_agent', 'uniphore_agent'],
    required_tools: ['scheduler_api', 'crm_lookup'],
    governance_tags: ['customer_facing'],
    strategic_weight: 0.21,
    drift_risk: 0.06,
    performance: {
      openai_agent: perf(0.94, 3.5, 800),
      salesforce_agent: perf(0.95, 4.2, 850),
      uniphore_agent: perf(0.93, 3.8, 900),
    },
  },
  {
    skill_id: 'skill_test_drive_followup_v1',
    name: 'Test-Drive Follow-Up',
    family: 'cx_triage',
    description: 'Personalized email/SMS follow-up after dealership test drive.',
    allowed_paths: ['openai_agent', 'salesforce_agent'],
    required_tools: ['crm_lookup'],
    governance_tags: ['customer_facing', 'gdpr_sensitive'],
    strategic_weight: 0.26,
    drift_risk: 0.09,
    performance: {
      openai_agent: perf(0.91, 4.0, 950),
      salesforce_agent: perf(0.92, 4.5, 1000),
    },
  },
  {
    skill_id: 'skill_loyalty_offer_v1',
    name: 'Loyalty Offer Generation',
    family: 'cx_triage',
    description: 'Generate next-best-offer per customer profile.',
    allowed_paths: ['openai_agent', 'anthropic_agent', 'salesforce_agent'],
    required_tools: ['crm_lookup', 'offer_catalog'],
    governance_tags: ['customer_facing', 'gdpr_sensitive'],
    strategic_weight: 0.31,
    drift_risk: 0.12,
    performance: {
      openai_agent: perf(0.88, 5.5, 1100),
      anthropic_agent: perf(0.87, 6.2, 1200),
      salesforce_agent: perf(0.89, 5.8, 1150),
    },
  },

  // ── events_ops (4) ─────────────────────────────────────
  {
    skill_id: 'skill_venue_incident_triage_v1',
    name: 'Venue Incident Triage',
    family: 'events_ops',
    description: 'Casino-floor / venue medical-event triage and escalation.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['venue_floorplan', 'incident_log'],
    governance_tags: ['safety_relevant', 'strategic_skill'],
    strategic_weight: 0.69,
    drift_risk: 0.15,
    performance: {
      hybrid_anthropic_human: perf(0.93, 35.0, 4800),
      human: perf(0.97, 125, 11500),
    },
  },
  {
    skill_id: 'skill_capacity_planning_v1',
    name: 'Venue Capacity Planning',
    family: 'events_ops',
    description: 'Forecast attendance, staffing, concession demand.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['attendance_history', 'weather_api'],
    governance_tags: [],
    strategic_weight: 0.43,
    drift_risk: 0.13,
    performance: {
      anthropic_agent: perf(0.85, 8.5, 1500),
      hybrid_anthropic_human: perf(0.93, 24.0, 3600),
    },
  },
  {
    skill_id: 'skill_show_run_v1',
    name: 'Show Run Coordination',
    family: 'events_ops',
    description: 'Cue-by-cue coordination across departments.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['rundown_doc', 'comms_radio_api'],
    governance_tags: ['strategic_skill'],
    strategic_weight: 0.58,
    drift_risk: 0.18,
    performance: {
      hybrid_anthropic_human: perf(0.91, 42.0, 5500),
      human: perf(0.96, 145, 12500),
    },
  },
  {
    skill_id: 'skill_responsible_gaming_intervention_v1',
    name: 'Responsible Gaming Intervention',
    family: 'events_ops',
    description: 'Detect & respond to problem-gambling indicators.',
    allowed_paths: ['hybrid_openai_human', 'human'],
    required_tools: ['player_history_api', 'rg_protocol_db'],
    governance_tags: ['gambling', 'regulatory', 'gdpr_sensitive', 'strategic_skill'],
    strategic_weight: 0.71,
    drift_risk: 0.22,
    performance: {
      hybrid_openai_human: perf(0.89, 31.0, 4500),
      human: perf(0.96, 115, 10800),
    },
  },

  // ── compliance (4) ─────────────────────────────────────
  {
    skill_id: 'skill_eu_ai_act_review_v1',
    name: 'EU AI Act High-Risk Review',
    family: 'compliance',
    description: 'Article 14 review of AI deployment.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['regulation_db', 'audit_trail_api'],
    governance_tags: ['regulatory', 'strategic_skill'],
    strategic_weight: 0.73,
    drift_risk: 0.16,
    performance: {
      hybrid_anthropic_human: perf(0.92, 55.0, 7200),
      human: perf(0.97, 185, 16500),
    },
  },
  {
    skill_id: 'skill_gdpr_dpia_v1',
    name: 'GDPR DPIA Drafting',
    family: 'compliance',
    description: 'Data-protection impact assessment for processing change.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['regulation_db', 'pii_redactor'],
    governance_tags: ['regulatory', 'gdpr_sensitive', 'strategic_skill'],
    strategic_weight: 0.65,
    drift_risk: 0.14,
    performance: {
      hybrid_anthropic_human: perf(0.91, 48.0, 6800),
      human: perf(0.96, 165, 15500),
    },
  },
  {
    skill_id: 'skill_soc2_evidence_v1',
    name: 'SOC 2 Evidence Collection',
    family: 'compliance',
    description: 'Quarterly evidence collation for CC6/CC7/CC8.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['audit_trail_api', 'change_log_db'],
    governance_tags: ['regulatory'],
    strategic_weight: 0.49,
    drift_risk: 0.10,
    performance: {
      anthropic_agent: perf(0.86, 11.5, 1900),
      hybrid_anthropic_human: perf(0.94, 32.0, 4600),
    },
  },
  {
    skill_id: 'skill_works_council_brief_v1',
    name: 'Works-Council Notification Brief',
    family: 'compliance',
    description: 'DE/FR works-council briefing prep for AI rollout.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['regulation_db', 'translation_api'],
    governance_tags: ['regulatory', 'gdpr_sensitive', 'strategic_skill'],
    strategic_weight: 0.68,
    drift_risk: 0.11,
    performance: {
      hybrid_anthropic_human: perf(0.93, 45.0, 6500),
      human: perf(0.97, 158, 14800),
    },
  },

  // ── field_service (4) ──────────────────────────────────
  {
    skill_id: 'skill_field_dispatch_v1',
    name: 'Field-Service Dispatch',
    family: 'field_service',
    description: 'Match incoming ticket to nearest qualified tech.',
    allowed_paths: ['openai_agent', 'salesforce_agent', 'cloudflare_agent'],
    required_tools: ['tech_locator', 'ticket_priority_api'],
    governance_tags: ['customer_facing'],
    strategic_weight: 0.34,
    drift_risk: 0.08,
    performance: {
      openai_agent: perf(0.92, 5.5, 1100),
      salesforce_agent: perf(0.93, 6.0, 1200),
      cloudflare_agent: perf(0.89, 3.8, 950),
    },
  },
  {
    skill_id: 'skill_downed_line_dispatch_v1',
    name: 'Downed-Line Emergency Dispatch',
    family: 'field_service',
    description: 'High-SLA emergency dispatch with safety pre-checks.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['tech_locator', 'safety_protocol_db'],
    governance_tags: ['safety_relevant', 'customer_facing'],
    strategic_weight: 0.61,
    drift_risk: 0.16,
    performance: {
      anthropic_agent: perf(0.83, 9.0, 1500),
      openai_agent: perf(0.82, 8.5, 1450),
      hybrid_anthropic_human: perf(0.93, 28.0, 4200),
    },
  },
  {
    skill_id: 'skill_install_quote_v1',
    name: 'Equipment Install Quote',
    family: 'field_service',
    description: 'Generate install quote with parts & labor.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'salesforce_agent'],
    required_tools: ['parts_catalog', 'labor_rate_db'],
    governance_tags: ['customer_facing'],
    strategic_weight: 0.29,
    drift_risk: 0.07,
    performance: {
      anthropic_agent: perf(0.89, 7.0, 1300),
      openai_agent: perf(0.88, 6.5, 1250),
      salesforce_agent: perf(0.90, 7.5, 1350),
    },
  },
  {
    skill_id: 'skill_pm_schedule_v1',
    name: 'Preventive Maintenance Scheduling',
    family: 'field_service',
    description: 'Auto-generate PM schedule based on duty-cycle.',
    allowed_paths: ['openai_agent', 'salesforce_agent', 'cloudflare_agent'],
    required_tools: ['duty_cycle_log', 'scheduler_api'],
    governance_tags: [],
    strategic_weight: 0.19,
    drift_risk: 0.05,
    performance: {
      openai_agent: perf(0.94, 4.0, 850),
      salesforce_agent: perf(0.95, 4.8, 950),
      cloudflare_agent: perf(0.92, 2.5, 700),
    },
  },

  // ── hr_people (4) ──────────────────────────────────────
  {
    skill_id: 'skill_q2_coaching_plan_v1',
    name: 'Q2 Coaching Plan',
    family: 'hr_people',
    description: 'Personal-development plan from performance data + 1:1 notes.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['hris_lookup', 'performance_db'],
    governance_tags: ['gdpr_sensitive', 'strategic_skill'],
    strategic_weight: 0.62,
    drift_risk: 0.13,
    performance: {
      hybrid_anthropic_human: perf(0.91, 32.0, 4600),
      human: perf(0.95, 125, 11200),
    },
  },
  {
    skill_id: 'skill_hiring_brief_v1',
    name: 'Hiring Brief Drafting',
    family: 'hr_people',
    description: 'Draft role spec from intake-meeting transcript.',
    allowed_paths: ['anthropic_agent', 'openai_agent', 'hybrid_anthropic_human'],
    required_tools: ['hris_lookup', 'job_arch_db'],
    governance_tags: ['gdpr_sensitive', 'customer_facing'],
    strategic_weight: 0.39,
    drift_risk: 0.11,
    performance: {
      anthropic_agent: perf(0.86, 8.5, 1500),
      openai_agent: perf(0.85, 7.9, 1450),
      hybrid_anthropic_human: perf(0.93, 24.0, 3700),
    },
  },
  {
    skill_id: 'skill_compensation_band_v1',
    name: 'Compensation Band Lookup',
    family: 'hr_people',
    description: 'Match role + region + level to comp band.',
    allowed_paths: ['anthropic_agent', 'openai_agent'],
    required_tools: ['comp_band_db', 'region_db'],
    governance_tags: ['gdpr_sensitive'],
    strategic_weight: 0.27,
    drift_risk: 0.06,
    performance: {
      anthropic_agent: perf(0.95, 5.0, 950),
      openai_agent: perf(0.94, 4.5, 900),
    },
  },
  {
    skill_id: 'skill_pip_review_v1',
    name: 'PIP Review',
    family: 'hr_people',
    description: 'Performance-improvement-plan progress review.',
    allowed_paths: ['hybrid_anthropic_human', 'human'],
    required_tools: ['hris_lookup', 'performance_db'],
    governance_tags: ['gdpr_sensitive', 'strategic_skill'],
    strategic_weight: 0.56,
    drift_risk: 0.18,
    performance: {
      hybrid_anthropic_human: perf(0.88, 38.0, 5200),
      human: perf(0.94, 145, 13500),
    },
  },
]

export function listSkillsByFamily(family: AEOSSkill['family']): AEOSSkill[] {
  return SKILLS.filter(s => s.family === family)
}

export function getSkillById(id: string): AEOSSkill | undefined {
  return SKILLS.find(s => s.skill_id === id)
}
